/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Leonan-Mac' at '9/20/16 9:56 PM' with Gradle 2.14.1
 *
 * @author Leonan-Mac, @date 9/20/16 9:56 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
